### PR TITLE
Support and tests for Django 1.9-1.11

### PR DESCRIPTION
**Pull request by jmbowman**
Added some fixes for compatibility with Django 1.9 through Django 1.11 and a couple of new test cases to help verify them:

* Stop using `request.REQUEST`, which is removed in Django 1.9.
* Support the new `MIDDLEWARE` setting in Django 1.10+ without dropping support for `MIDDLEWARE_CLASSES`.
* Added support for testing Django 1.8 through 1.11 via `tox`; this also required adding `manage.py`, a `test_settings.py` module, and a few requirements files.
* Indicate the supported Django versions in `setup.py`.
* Added 2 new test cases to help verify the changes.

Test coverage is still only 56%, but that's up from 32% prior to this PR.

### CODE REVIEW

**Comment by pdpinch** [comment]
@jmbowman does edx-platform have a dependency on this? 

@amir-qayyum-khan can you do a review? You were testing another CAS issue recently, right?

**Comment by jmbowman** [comment]
@pdpinch Yes, [it does](https://github.com/edx/edx-platform/blob/master/lms/envs/common.py#L2474).  This is part of the push to get edx-platform on Django 1.11 before the Hawthorn release.

**Review by amir-qayyum-khan — APPROVED** [review]

**Comment by pdpinch** [comment]
Ok, @amir-qayyum-khan or I can merge this but... @jmbowman how are you pulling this into edX? Are you specifying the github tag or do you need a release to PyPI or.... ?

**Comment by jmbowman** [comment]
@pdpinch  We're currently [specifying an exact git hash](https://github.com/edx/edx-platform/blob/master/requirements/edx/github.txt#L58) (which is for the current head commit on master).  So you can merge this anytime, and we'll just update edx-platform to use the new hash after that (which will run tests on the PR that changes it).

I'd think we'll eventually want a new version number, but it hasn't changed in 6 years, so there probably isn't a strong need to increment it now.

**Comment by pdpinch** [comment]
@jmbowman merged afac57bc523f145ae826f4ed3d4fa8b2c86c5364

**Pull request merged**
